#! /usr/bin/env python

import sys
import os
import subprocess
import argparse

def callcmd(cmd = ''):
	ret = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE).stdout.read()
	return ret;

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='option_name')

    mount_parser = subparsers.add_parser('mount', help="Mount a snap")
    mount_parser.add_argument("snapname", help="Snap to be mounted.")
    mount_parser.add_argument("-cscope", help="Run cscope as well.")

    search_parser = subparsers.add_parser('search', help='Start a cscope on a snap.')
    search_parser.add_argument("snapname", help="Snap to be searched.")

    rebuild_parser = subparsers.add_parser('rebuild', help='Rebuild the snap symbol db')
    rebuild_parser.add_argument("snapname", help='Snap for which we rebuild.')

    args = parser.parse_args()

    print args, mount_parser

    if args.option_name == 'mount' and args.snapname : 
        print "CVH: Mounting :", args.snapname
        cmd = 'mkdir /source/'+args.snapname
        callcmd(cmd)
        cmd = 'mount usnfs03.commvault.com:/build/11.0/Build80_'+args.snapname + ' /source/'+args.snapname
        callcmd(cmd)
        cmd = '/home/gbuilder/.dotfile/gen_cscope.sh '+args.snapname
        callcmd(cmd)

    if args.option_name == 'search' and args.snapname : 
        print 'searching ' + args.snapname
        cmd = 'cd /BROWSE'
        callcmd(cmd)
        cmd = 'rm -f /BROWSE/cscope*'
        callcmd(cmd)
        cmd = 'ln -s /BROWSE/'+args.snapname+'/cscope.out /BROWSE/cscope.out'
        callcmd(cmd)
        cmd = 'ln -s /BROWSE/'+args.snapname+'/cscope.in.out /BROWSE/cscope.in.out'
        callcmd(cmd)
        cmd = 'ln -s /BROWSE/'+args.snapname+'/cscope.po.out /BROWSE/cscope.po.out'
        callcmd(cmd)
        cmd = 'ln -s /BROWSE/'+args.snapname+'/tags /BROWSE/tags'
        callcmd(cmd)
        cmd = 'cscope -d -f /BROWSE/cscope.out'
        os.system(cmd)

    if args.option_name == 'rebuild' and args.snapname :
        print 'Rebuilding ' + args.snapname
        cmd = '/home/gbuilder/.dotfile/gen_cscope.sh '+args.snapname
        callcmd(cmd)
        cmd = 'rm -f /BROWSE/cscope*'
        callcmd(cmd)
        cmd = 'ln -s /BROWSE/'+args.snapname+'/cscope.out /BROWSE/cscope.out'
        callcmd(cmd)
        cmd = 'ln -s /BROWSE/'+args.snapname+'/cscope.in.out /BROWSE/cscope.in.out'
        callcmd(cmd)
        cmd = 'ln -s /BROWSE/'+args.snapname+'/cscope.po.out /BROWSE/cscope.po.out'
        callcmd(cmd)
        callcmd(cmd)
        cmd = 'ln -s /BROWSE/'+args.snapname+'/tags /BROWSE/tags'

